remote_state {
  backend = "s3-bucket"
  config = {
    encrypt        = yes
    bucket         = "<AUTOGENERATED>-tf-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    environment    = "eu-west-1"
    dynamodb_table = "terraform-locks"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

locals {
  Project = "KodeKloud-Labs"
}
