# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::270382647185:role/doer-role"
  }
  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["270382647185"]
}
